// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zcmbATbSh-GtEmZiOolyV8m2EU5axlQ',
    appId: '1:602636559852:web:5ee4c56107add3a6044cc9',
    messagingSenderId: '602636559852',
    projectId: 'delivery-app-be449',
    authDomain: 'delivery-app-be449.firebaseapp.com',
    storageBucket: 'delivery-app-be449.appspot.com',
    measurementId: 'G-R08JM9MB7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNyb2bjogjHf4wHjLWepW8wHMNSyC-GQk',
    appId: '1:602636559852:android:fe29e46e9e07c2be044cc9',
    messagingSenderId: '602636559852',
    projectId: 'delivery-app-be449',
    storageBucket: 'delivery-app-be449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEO2qFvCEuOthGcNp8qRGUWeoYEBU6cfQ',
    appId: '1:602636559852:ios:b47dfddcb3098d4c044cc9',
    messagingSenderId: '602636559852',
    projectId: 'delivery-app-be449',
    storageBucket: 'delivery-app-be449.appspot.com',
    androidClientId: '602636559852-5uqdpk20gmiq4ri0n804nnq5v58j0m6e.apps.googleusercontent.com',
    iosClientId: '602636559852-mt1543o1rsm52iq27a0k8953slnmq004.apps.googleusercontent.com',
    iosBundleId: 'com.deliveryapp.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEO2qFvCEuOthGcNp8qRGUWeoYEBU6cfQ',
    appId: '1:602636559852:ios:7d22b86f36bf5637044cc9',
    messagingSenderId: '602636559852',
    projectId: 'delivery-app-be449',
    storageBucket: 'delivery-app-be449.appspot.com',
    androidClientId: '602636559852-5uqdpk20gmiq4ri0n804nnq5v58j0m6e.apps.googleusercontent.com',
    iosClientId: '602636559852-brsqf3emva29k0jo912nsgb685u4eet3.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverapp.RunnerTests',
  );
}
